### PR TITLE
update Bingham Center give button to go to donate page, closes TASK24…

### PR DESCRIPTION
**Pull request by seanaery**
…42587

### CODE REVIEW

**Comment by mikedaul** [comment]
Hi Sean - I pulled this branch onto Pre. The bingham center page seems to not be in there for some reason :(

Was there anything you actually needed to review, or was this a pretty minor change? We could recreate the page on Pre if needed...

**Review by mikedaul — APPROVED** [review]
Looks fine to me!

**Comment by seanaery** [comment]
@mikedaul Super minor change! Just changed a link. No need to test / recreate a page :-)

**Comment by mikedaul** [comment]
Cool - I've merged and deployed: https://library.duke.edu/rubenstein/bingham/

**Pull request merged**
